### ISSUE TITLE
Slack member deactivation

### ISSUE THREAD

**Issue by hderp886** [warlof/slackbot#4]
I came across an issue today that if people leave, they are still members of the team and can still access the default channel.

Is there a way to auto deactivate a member if none of the filters return true?

**Comment by warlof** [comment]
Unfortunately the slack api doesn't provide such feature except for
business plan which isn't the aim of this package.

My personnal recommandation is to set the default channel as public channel
and create private channel for restricted content.

Le 31 août 2016 6:22 PM, "hderp886" <notifications@github.com> a écrit :

I came across an issue today that if people leave, they are still members
of the team and can still access the default channel.

Is there a way to auto deactivate a member if none of the filters return
true?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/warlof/slackbot/issues/4>, or mute the thread
